server:
  port: 8060

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8061/eureka/

logging:
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} ${LOG_LEVEL_PATTERN:-%5p} %m%n"

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/user/**
          filters:
            - RewritePath=/user/(?<path>.*), /$\{path}
        - id: wallet-service
          uri: lb://wallet-service
          predicates:
            - Path=/wallet/**
          filters:
            - RewritePath=/wallet/(?<path>.*), /%\{path}
        - id: fund-service
          uri: lb://fund-service
          predicates:
            - Path=/fund/**
          filters:
            - RewritePath=/wallet/(?<path>.*), /%\{path}